### PR TITLE
Fixed a bug when there is no argument called env

### PR DESCRIPTION
**Pull request by tiagofrepereira2012**

### CODE REVIEW

**Comment by siebenkopf** [comment]
I wonder why the ``env`` wouldn't be in the ``args``... Usually, when the command line parser does not get an argument ``--env``, ``args.env`` will be ``[]`` (the default), but it will still exist:
https://github.com/bioidiap/bob.bio.base/blob/master/bob/bio/base/tools/command_line.py#L143

**Comment by tiagofrepereira2012** [comment]
Long story short, the `bob.spoof.base` package (https://gitlab.idiap.ch/pkorshunov/bob.spoof.base/) uses the bob.bio.base package for several tasks (one of them is to deal with grid submission).

This package has its own command line tools and injects an argparse object to the `GridSubmission` class (with no `env` argument). 

Obviously I didn't know that, the package is not in nightlies (no way to integrate test this) and the software crashed.

**Comment by siebenkopf** [comment]
So, why don't you change that according package than, instead of hacking something into ``bob.bio.base`` that does not make much sense?

**Comment by tiagofrepereira2012** [comment]
The package `bob.spoof.base` is already under refactoring to better reuse the command line tools, so this will not be an issue anymore

**Comment by siebenkopf** [comment]
So, can we revert this one?

**Comment by tiagofrepereira2012** [comment]
Not now, there are people using this feature right now

**Comment by tiagofrepereira2012** [comment]
Well, I will put @pkorshunov  in the thread, because he is the guy from this one.

**Pull request merged**
